apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rdicidr
  namespace: production
spec:
  serviceName: "rdicidr-service"
  replicas: 3
  selector:
    matchLabels:
      app: rdicidr
  template:
    metadata:
      labels:
        app: rdicidr
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: rdicidr
        image: carpio701021/rdicidr-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: MY_SECRET
          valueFrom:
            secretKeyRef:
              name: rdicidr-secret
              key: MY_SECRET
